version: '3.8'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    command: >
      sh -c "
        npx prisma migrate dev --name init &&
        npm run start:dev
      "
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: template
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
